### ISSUE TITLE
Allow embedding via YouTube shortlink

### ISSUE THREAD

**Issue by tobenschmidt** [embedas/go-embed#1]
Currently it is not possible to embed a video via YouTube shortlink like _https://youtu.be/VIDEOID_. Instead the long link like https://www.youtube.com/watch?v=YOUTUBEID is required. It would be great to have support for YouTube shortlinks.

**Comment by thebaer** [comment]
Thanks for reporting this! Just updated the library to support these shortlinks. That fix should be live on Write.as later today.

**Comment by tobenschmidt** [comment]
Thanks for adding YouTube shortlink support so quickly! I can confirm that this is working now on Write.as.
